import pandas as pd
import os
import sys

# Add parent directory to path to import config_loader
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)

try:
    from config_loader import get_config
except ImportError:
    # Fallback if config_loader not available (though it should be)
    print("Warning: Could not import config_loader. Using defaults.")
    def get_config():
        return {
            'features': {
                'sma_periods': [20, 50],
                'rsi_period': 14,
                'volatility_window': 20,
                'macd_fast': 12,
                'macd_slow': 26
            }
        }

def generate_features(ticker="AAPL"):
    """
    Loads cleaned data, adds technical indicators, and saves the final dataset.
    
    Parameters:
        ticker (str): The stock or ETF symbol (default: "AAPL").
    """
    
    # Get configuration
    config = get_config()
    features_config = config.get('features', {})
    
    # define paths
    # define paths
    processed_dir = config['paths']['processed_data_dir']
    input_path = f"{processed_dir}/{ticker}_cleaned.csv"
    output_dir = processed_dir
    output_path = f"{output_dir}/{ticker}_final.csv"
    
    print(f"Generating features for {ticker}...")
    
    # load cleaned data
    try:
        df = pd.read_csv(input_path, index_col='date', parse_dates=True)
    except FileNotFoundError:
        print(f"Error: File not found at {input_path}")
        return

    # 1. Daily Returns (percentage change)
    df['daily_return'] = df['close'].pct_change()

    # 2. Moving Averages (Dynamic from config)
    sma_periods = features_config.get('sma_periods', [20, 50])
    for period in sma_periods:
        df[f'ma_{period}'] = df['close'].rolling(window=period).mean()

    # 3. RSI (Dynamic period from config)
    rsi_period = features_config.get('rsi_period', 14)
    delta = df['close'].diff()
    up = delta.clip(lower=0)
    down = -1 * delta.clip(upper=0)
    ma_up = up.ewm(com=rsi_period-1, adjust=False, min_periods=rsi_period).mean()
    ma_down = down.ewm(com=rsi_period-1, adjust=False, min_periods=rsi_period).mean()
    rs = ma_up / ma_down
    df[f'rsi_{rsi_period}'] = 100 - (100 / (1 + rs))

   # 4. MACD (Dynamic from config)
    macd_fast = features_config.get('macd_fast', 12)
    macd_slow = features_config.get('macd_slow', 26)
    
    exp1 = df['close'].ewm(span=macd_fast, adjust=False).mean()
    exp2 = df['close'].ewm(span=macd_slow, adjust=False).mean()
    df['macd'] = exp1 - exp2

    # 5. Volatility (Dynamic window from config)
    vol_window = features_config.get('volatility_window', 20)
    df['volatility'] = df['daily_return'].rolling(window=vol_window).std() 

    # drop rows with NaN values generated by rolling windows and pct_change
    df.dropna(inplace=True)
    

    # save to csv
    df.to_csv(output_path)
    print(f"Feature-engineered data saved to {output_path}")

def generate_intraday_features(ticker="AAPL", interval="5m"):
    """
    Generates features for intraday data.
    """
    # Get configuration
    config = get_config()
    # Use standard features config for now, or could have specific intraday settings
    features_config = config.get('features', {})
    
    processed_dir = os.path.join(config['paths']['processed_data_dir'], "intraday")
    input_path = f"{processed_dir}/{ticker}_{interval}_cleaned.csv"
    output_path = f"{processed_dir}/{ticker}_{interval}_final.csv"
    
    print(f"Generating intraday features for {ticker} ({interval})...")
    
    try:
        df = pd.read_csv(input_path, index_col='date', parse_dates=True)
    except FileNotFoundError:
        print(f"Error: File not found at {input_path}")
        return

    # Use shorter windows for intraday to be more reactive?
    # For now sticking to configured defaults but logic could be added here
    
    # 1. Returns
    df['return'] = df['close'].pct_change()
    
    # 2. Moving Averages
    # Maybe use shorter periods for intraday like 5, 20
    for period in [5, 20]:
         df[f'sma_{period}'] = df['close'].rolling(window=period).mean()
    
    # 3. RSI
    rsi_period = 14
    delta = df['close'].diff()
    up = delta.clip(lower=0)
    down = -1 * delta.clip(upper=0)
    ma_up = up.ewm(com=rsi_period-1, adjust=False, min_periods=rsi_period).mean()
    ma_down = down.ewm(com=rsi_period-1, adjust=False, min_periods=rsi_period).mean()
    rs = ma_up / ma_down
    df[f'rsi_{rsi_period}'] = 100 - (100 / (1 + rs))

    # 4. Volatility
    df['volatility'] = df['return'].rolling(window=20).std()

    df.dropna(inplace=True)
    df.to_csv(output_path)
    print(f"Intraday features saved to {output_path}")

if __name__ == "__main__":
    generate_features()
